export const SOCKET_EVENT = {
  // Lobby Socket Events
  JOIN_LOBBY: 'JOIN_LOBBY',
  LEAVE_LOBBY: 'LEAVE_LOBBY',
  LOBBY_CHAT: 'LOBBY_CHAT',

  // Note Socket Events
  JOIN_NOTE: 'JOIN_NOTE',
  LEAVE_NOTE: 'LEAVE_NOTE',
  NOTE_CHAT: 'NOTE_CHAT',

  // Note Socket Events - WebRTC
  NEW_USER: 'NEW_USER',
  SEND_OFFER: 'SEND_OFFER',
  RECEIVED_OFFER: 'RECEIVED_OFFER',
  SEND_ANSWER: 'SEND_ANSWER',
  RECEIVED_ANSWER: 'RECEIVED_ANSWER',
  SEND_ICE_CANDIDATE: 'SEND_ICE_CANDIDATE',
  RECEIVED_ICE_CANDIDATE: 'RECEIVED_ICE_CANDIDATE',
} as const;

export type Event = (typeof SOCKET_EVENT)[keyof typeof SOCKET_EVENT];
