export const SOCKET_EVENT = {
  // Note Socket Events
  JOIN_NOTE: 'JOIN_NOTE',
  LEAVE_NOTE: 'LEAVE_NOTE',
  LEFT_NOTE: 'LEFT_NOTE',
  NOTE_CHAT: 'NOTE_CHAT',

  // Note Socket Events - WebRTC
  EXISTING_NOTE_USERS: 'EXISTING_NOTE_USERS',
  NEW_USER: 'NEW_USER',
  SEND_OFFER: 'SEND_OFFER',
  RECEIVED_OFFER: 'RECEIVED_OFFER',
  SEND_ANSWER: 'SEND_ANSWER',
  RECEIVED_ANSWER: 'RECEIVED_ANSWER',
  SEND_ICE_CANDIDATE: 'SEND_ICE_CANDIDATE',
  RECEIVED_ICE_CANDIDATE: 'RECEIVED_ICE_CANDIDATE',

  // Note Socket Events - CRDT
  CRDT_INIT: 'CRDT_INIT',
  LOCAL_INSERT: 'LOCAL_INSERT',
  LOCAL_DELETE: 'LOCAL_DELETE',
  LOCAL_UPDATE: 'LOCAL_UPDATE',
  REMOTE_INSERT: 'REMOTE_INSERT',
  REMOTE_DELETE: 'REMOTE_DELETE',
  REMOTE_UPDATE: 'REMOTE_UPDATE',
} as const;
